### ISSUE TITLE
Login failed with TypeError: Cannot read property 'click' of null

### ISSUE THREAD

**Issue by saurabhnsonar** [orlopau/sunnyportal_scraper#1]
The chromium continues to reload with error even after successful login:

Login failed with TypeError: Cannot read property 'click' of null
relogging...

Can you please assist me solving this?

**Comment by saurabhnsonar** [comment]
Thanks for update this time I am getting issue with duplicate types after update PS. https://cl.ly/syCf
also I have multiple PV system so after login I get all list of all PV systems on page rather than getting a dashboard. How can I handle that?

**Comment by orlopau** [comment]
I would like to support multiple PV systems, but I can't test the program on multiple PV plants because I only have one. Do you know of a demo sunnyportal website by SMA?

Your issue with logging in didnt appear in my testing yet, but I will look into it.

**Comment by saurabhnsonar** [comment]
Hello,

Yes I have multiple accounts with 2-5 pv systems enabled on it. So looking for that. I went through your code even I am trying to build front panels gui using that.

**Comment by orlopau** [comment]
I build the same thing using this code. Maybe you can add the functionality yourself, but the code is pretty bad because of all the errors that can arise when using a webbrowser. Prior to that script you could actually just send a some GET requests to mimic the functionality of the website but they somehow disabled that so a real browser is the only way i could come up with.

**Comment by saurabhnsonar** [comment]
Yes i too saw that, even I tried using php setting browser agents but that too failed to work.

**Comment by orlopau** [comment]
I changed the method of navgation so the program doesnt rely on the buttons being present anymore. Maybe that helps.
